/**
 * Este compilador foi criado com o intuito de facilitar o preparo do arquivo
 * de dados recebido (planilha Excel).
 *
 * Vez ou outra o governo solicita dados acadêmicos para atualização de status
 * de bolsas de assistência. Junto com a solicitação vem um arquivo PDF de
 * layout com a especificação da formatação dos dados que devem ser enviados.
 * A UDO solicita os dados à ASSEST (Assessoria à Assistência Estudantil), que
 * os puxa do SAGRES, devolvendo-os numa planilha do Excel.
 * A planilha reflete uma tabela do SAGRES e contém dados pessoais de alunos da
 * UESC. A tabela vem organizada com os mesmo cabeçalhos de coluna que são
 * exigidos no arquivo de layout, porém os dados estão em outro formato.
 *
 * Após os ajustes dos dados, a planilha resultante deve ser submetido no site
 * <http://maisfuturo.educacao.ba.gov.br/auth/>.
 *
 * ==== Regras aplicadas pelo programa (em sequência, separadas em grupos) ====
 *
 * 1. Remover registros que possuem CPF (`E_CPF`) ou RH (`E_RG`) nulos (NULL);
 *
 * 2. Alterar todos os casos nulos de órgão expeditor (`E_ORGAO_EXPEDIDOR_RG`)
 * para "SSP";
 *
 * 3. Limpar todos os registros das colunas `E_CADUNICO` e `E_NIS`, atribuindo
 * "" (string vazia) nos campos;
 *
 * 4. Fazer a correspondência dos códigos em `E_TURNO_ATUAL` seguindo a legenda:
 * 1 = Matutino 2 = Vespertino 3 = Noturno 4 = Integral/diurno
 *
 * 5. Aplicar máscara em `E_INGRESSO_ANO_SEMESTRE` alterando o formato "99999"
 * para "9999.9";
 *
 * 6. Fazer a correspondência dos códigos em `E_COR_RACA` seguindo a legenda: 1
 * = Branca 2 = Preta 3 = Amerela (é 'AmErela' mesmo) 4 = Parda 5 = Indígena 6 =
 * Não Declarado / null
 *
 * 7. Alterar todos os registros da coluna `E_UNIVERSIDADE` para "4" (valor
 * correspondente à UESC);
 *
 * 8. Alterar todos os registros da coluna `E_CAMPUS` para "Prof. Soane Nazaré
 * de Andrade";
 *
 * 9. Limpar todos os registros das colunas `E_COMPLEMENTO`, `E_MUNICIPIO_IBGE`,
 * `E_CEP`, `E_ZONA`, `E_TELEFONE` e `E_CELULAR` atribuindo "" (string vazia)
 * nos campos;
 *
 * 10. Limpar todos os registros das colunas `R_CPF`, `R_RG`,
 * `R_ORGAO_EXPEDIDOR_RG`, `R_DATA_NASCIMENTO`, `R_NIS`, `R_LOGRADOURO`,
 * `R_NUMERO`, `R_BAIRRO`, `R_COMPLEMENTO`, `R_MUNICIPIO_IBGE`, `R_CEP`,
 * `R_ZONA`, `R_TELEFONE`, `R_CELULAR` e `R_EMAIL`;
 *
 * 11. Remover as primeiras linhas (cabeçalhos).
 *
 */
package br.uesc.maisfuturocompiler;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Giovanne Almeida 19/09/2018
 */
public class MainFrame extends javax.swing.JFrame {

    private String inputDirectory = "";
    private String outputDirectory = "";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        txtInput = new javax.swing.JTextField();
        btExploreInput = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOutput = new javax.swing.JTextField();
        btCompile = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mais Futuro Compiler");
        setBounds(new java.awt.Rectangle(400, 200, 508, 520));
        setMinimumSize(new java.awt.Dimension(508, 520));
        setSize(new java.awt.Dimension(508, 520));

        btExploreInput.setText("Procurar...");
        btExploreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExploreInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Arquivo de origem");

        jLabel4.setText("Diretório de destino");

        txtOutput.setEditable(false);

        btCompile.setText("Compilar");
        btCompile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompileActionPerformed(evt);
            }
        });

        jLabel3.setText("Log de eventos");

        txtLog.setEditable(false);
        txtLog.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 303, Short.MAX_VALUE))
                    .addComponent(txtInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExploreInput))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtOutput)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCompile)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExploreInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btCompile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btCompile.getAccessibleContext().setAccessibleDescription("btCompile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExploreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExploreInputActionPerformed
        outputDirectory = "";
        //Cria a janela de seleção de arquivo
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos Excel 2007", "xlsx");
        jfc.setFileFilter(filter);

        //Abre a janela de seleção de arquivo
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            inputDirectory = selectedFile.getAbsolutePath();
            txtInput.setText(inputDirectory);
            //Pega o caminho até o arquivo selecionado para criar o caminho de destino
            String[] folders = selectedFile.getParent().split("\\\\");
            for (String folder : folders) {
                outputDirectory = outputDirectory.concat(folder + "\\");
            }
            //Aplica a extensão do arquivo ao arquivo de destino
            int i = selectedFile.getName().lastIndexOf('.');
            if (i > 0) {
                outputDirectory = outputDirectory.concat(selectedFile.getName().substring(0, i) + "_arrumado" + selectedFile.getName().substring(i));
            }

            txtOutput.setText(outputDirectory);
        }
    }//GEN-LAST:event_btExploreInputActionPerformed

    private void btCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompileActionPerformed
        //Inicializa a área de log
        LogHelper.getInstance().setTxtLog(txtLog);
        btCompile.setEnabled(false);
        btExploreInput.setEnabled(false);
        //Começa a compilação
        new Compiler().run(inputDirectory, outputDirectory, progressBar, new OnCompileListener() {
            @Override
            public void onFinished(int status) {
                if (status == OnCompileListener.COMPILE_SUCCESS) {
                    LogHelper.getInstance().writeInConsole("Compilação concluída com êxito.");
                    JOptionPane.showMessageDialog(MainFrame.this, "Um arquivo de log foi gerado no local do arquivo de origem.", "Compilação concluída", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    LogHelper.getInstance().writeInConsole("Falha na compilação.");
                    JOptionPane.showMessageDialog(MainFrame.this, "Ocorreu uma falha durante a compilação", "A compilação falhou", JOptionPane.INFORMATION_MESSAGE);
                }
                btCompile.setEnabled(true);
                btExploreInput.setEnabled(true);
            }

            @Override
            public void onFileNotFound(String title, String message) {
                JOptionPane.showMessageDialog(MainFrame.this,
                        message,
                        title,
                        JOptionPane.ERROR_MESSAGE);
            }
        });
    }//GEN-LAST:event_btCompileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompile;
    private javax.swing.JButton btExploreInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
